### ISSUE TITLE
Tweaking SignalR for beta releases? 

### ISSUE THREAD

**Issue by heathyates** [aspnet/SignalR-Server#109] opened 2015-07-29 17:02 UTC
I am aware that no further work really will be done to Signal R as it relates to ASP.NET 5 until post RTM. Given this, is there anyway SignalR can be made friendly to each beta release so it does not introduce breaking changes to ASP.NET5 beta applications? 

As it stand now, I have some basic signalR features in my beta MVC application. Since I recently just upgraded to beta 6, SignalR has the current potential to tank my application by bringing in unintended beta 5 packages since no beta6 version exists. 

If this is something not in the cards moving forward for any future beta releases, or can something be done? I would appreciate a definitive answer and thank you for your time and efforts.

**Comment by Eilon** [comment] 2015-07-29 17:11
@DamianEdwards @davidfowl

**Comment by heathyates** [comment] 2015-07-29 18:17
Thanks @Eilon . :)

**Comment by vcsjones** [comment] 2015-07-29 18:50
I would also like this to be considered. I have a hard dependency on SignalR for my vNext app, and will be stuck on beta5 until a new beta is SignalR.Server is available.

**Comment by Tragetaschen** [comment] 2015-07-29 19:10
It's the same for me. I will do the necessary work to have it running against future releases at least in its current state. So it would be great if there's a way to give that back.

A couple of thoughts:

It's only two breaking-change-releases according to The Plan. After that it's following the RC(s) which has a high probability of requiring only project.json changes.

It's probably a good idea to go to a .1-alpha* to make the current status crystal clear.

The changes I make will lag behind the official other releases depending on when I can move to the ASP.NET releases.

**Comment by heathyates** [comment] 2015-07-29 20:57
@Eilon @DamianEdwards @davidfowl Found it [here](https://www.myget.org/gallery/aspnetmaster). It's on the aspnetmaster for nugget.

**Comment by Eilon** [comment] 2015-07-29 21:34
@heathyates the SignalR that's on aspnetmaster is somewhat out of date - I'm not sure how well it works at this point.

**Comment by heathyates** [comment] 2015-07-29 21:38
@Eilon *nods* Well, if that is the case, then I think my initial question on this issue is relevant and I politely request it remain open.

**Comment by Eilon** [comment] 2015-07-29 21:44
Yeah don't worry not going to close this until the issue is resolved :smile:

**Comment by Aequoris** [comment] 2015-08-14 04:57
I too would like it updated for beta6 and I am happy to help out for the same reasons as the other posters.

It is critical functionality for one of my own vnext apps. :)

**Comment by davidfowl** [comment] 2015-08-14 05:00
Not sure what is being asked for here. We're going to make sure SignalR compiles but we're not doing any testing and there are a bunch of known issues right now.

**Comment by davidfowl** [comment] 2015-08-14 05:03
> I too would like it updated for beta6 and I am happy to help out for the same reasons as the other posters.

One very large work item is porting all of the functional tests from https://github.com/SignalR/SignalR/ to this repo.

**Comment by gustavomick** [comment] 2015-08-14 05:23
i think, as a community we need a formal mitigation strategy. we are talking about 12 to 18 months until we can see signalr support back again.
comparing to other frameworks that right now are highly evolved... im doubtful about this path.

**Comment by davidfowl** [comment] 2015-08-14 05:40
The only reasonable thing in the short term would be to use the Owin adapter + the IAppBuilder bridge to run SignalR 2.2 on ASP.NET 5 /cc @DamianEdwards

**Comment by heathyates** [comment] 2015-08-14 20:22
@davidfowl "We're going to make sure SignalR compiles". I translate thait to meant that when we move to beta7, you will make sure SignalR compiles for beta7 and doesn't bring any dependencies with previous beta versions (which could tank your app). Yes?

**Comment by BalassaMarton** [comment] 2015-10-02 07:40
Is there any progress on this? We have already put huge effort into our vNext project that uses SignalR, but now we have no plan. Going back to MVC 5 is not an option. We could use SignalR 2, but I couldn't find any references on how to do that. @davidfowl can you provide some information about the IAppBuilder bridge you mentioned?

**Comment by oryol** [comment] 2015-10-29 18:36
@davidfowl @Eilon 
Is it possible to release ASP .Net 5 Betta8 compatible version on the NuGet? Or should we build it manually?

**Comment by Eilon** [comment] 2015-11-02 04:55
@oryol at this point if you can get something working we'd be happy to work with you on a pull request.

**Comment by moozzyk** [comment] 2016-08-24 22:40
No longer relevant.

**Closed by moozzyk** 2016-08-24 22:40 UTC
