### ISSUE TITLE
Cannot read property 'client' of undefined

### ISSUE THREAD

**Issue by ljruiten** [aspnet/SignalR-Server#180] opened 2016-05-20 14:03 UTC
I am working with ASP.NET Core RC2 and I have been trying to get rid of this error since yesterday.

The javascript files are included in the following order:
```
<script src="/js/jquery-2.2.0.js"></script>
<script src="/js/jquery.signalR-2.2.0.js"></script>
<script src="/signalr/hubs" type="text/javascript"></script>
```

The hub is created like this and the TypeError is thrown at the hub.client.receive line.
```
var that = this;
var hub = $.connection.guacHub;

$.connection.hub.logging = true;
$.connection.hub.error(function (error) {
    console.log('SignalR error: ' + error)
});

hub.client.Receive = function (elements) {
    // Get opcode
    var opcode = elements.shift();
    // Call instruction handler.
    if (that.oninstruction)
        that.oninstruction(opcode, elements);
};
```

This is what my Hub looks like:
```
public class GuacHub : Hub {
    public Dictionary<string, GuacClient> GuacClients = new Dictionary<string, GuacClient>();

    public override Task OnConnected() {
        lock (GuacClients) {
            GuacClient client = new GuacClient(this.Context.ConnectionId);
            GuacClients.Add(client.Id, client);
            client.Start();
        }
        return base.OnConnected();
    }
   //Other  functions
```
Some other points:
- This code runs fine in another project with the full .NET Framework
- If I manually go to /signalr/hubs it works and does not give me a 404
- All of the includes work
- I have tried setting the HubName with the attribute
- I have tried every form of the hubname with camelcase / no camelcase etcetera

**Comment by Megasware128** [comment] 2016-05-29 23:50
Got the same problem. But we will have to wait after ASP.NET Core RTM before active development will happen here.

**Comment by Robynhu** [comment] 2016-06-04 23:58
Same problem here. Was working well on RC1.

**Comment by Robynhu** [comment] 2016-06-05 01:10
Guys, this work for me...

https://github.com/aspnet/SignalR-Server/issues/164

http://stackoverflow.com/questions/37475825/upgrading-to-rc2-with-signalr-3-0-results-in-invalidoperationexception-progre

I hope this could help in the same way that helped me

**Comment by moozzyk** [comment] 2016-06-06 23:32
Possibly a dupe of https://github.com/aspnet/SignalR-Server/issues/164

**Comment by mspratap6** [comment] 2016-06-30 06:53
Thanks @Robynhu ,

I was also facing the same issue with signalR on Asp.net Core Rc2 , 
earlier i was using  `"Microsoft.AspNetCore.SignalR.Server": "0.1.0-rc2-20896" `

Now Added `<add key="Code Comb" value="https://www.myget.org/F/codecomb-rc2/api/v3/index.json" />`

and Changed signalR package to `"Microsoft.AspNetCore.SignalR.Server": "0.1.0-rc2-final",`

Now issue is resolved and signalR is working fine.

**Closed** 2016-08-25 21:51 UTC
Labels: duplicate
