### ISSUE TITLE
$.connection.chatHub is not defined

### ISSUE THREAD

**Issue by papadi** [aspnet/SignalR-Server#193] opened 2016-07-06 16:17 UTC
I'm trying to write the chat sample (http://www.asp.net/signalr/overview/getting-started/tutorial-getting-started-with-signalr) using version 0.1.0-rc2-20896 of SignalR and version 1.0.0-rc2-final of asp.net core.

I have added the following into my startup class:

    app.UseSignalR();
    services.AddSignalR(options => { options.Hubs.EnableDetailedErrors = true; });

And my Hub looks like this:

    public class ChatHub : Hub
    {
        public void Send(string name, string message)
        {
            // Call the broadcastMessage method to update clients.
            Clients.All.broadcastMessage(name, message);
        }
    }

The client side file is generated (/signalr/hubs) and $.connection is defined, but not $.connection.**c**hatHub or $.connection.**C**hatHub

Any ideas?

**Comment by AndreiGorlov** [comment] 2016-07-08 20:08
Works fine with "Microsoft.AspNetCore.SignalR.Server": "0.1.0-rtm-21431" on ASP.NET Core 1.0.0. Also worked for me on rc2, AFAIR.

**Comment by moozzyk** [comment] 2016-08-25 21:58
This seems to be a duplicate of #180. I tried and it worked for me. If you still see this with the latest version feel free to reopen.

**Closed by moozzyk** 2016-08-25 21:58 UTC
