### ISSUE TITLE
"Hub could not be resolved" on .NET Core

### ISSUE THREAD

**Issue by AndreiGorlov** [aspnet/SignalR-Server#164] opened 2016-04-07 10:05 UTC
One more attempt to migrate my project from dnx to dotnet cli... (previous attempt https://github.com/aspnet/SignalR-Server/issues/154)
Again got exception when accessing api controller that injects IHubContext<>.
```
System.InvalidOperationException: 'MyHub' Hub could not be resolved.
   at Microsoft.AspNetCore.SignalR.Hubs.HubManagerExtensions.EnsureHub(IHubManager hubManager, String hubName, IPerformanceCounter[] counters)
```
Here is repro:
https://github.com/AndreiGorlov/cli-samples/tree/signalr-sandbox/HelloMvcApi
dotnet restore -> dotnet run -> hit http://localhost:5000/api/products -> boom!

When publishing for full .net framework (https://github.com/AndreiGorlov/cli-samples/tree/signalr-sandbox/HelloMvcApiFull) - everything works fine, but if I set "preserveCompilationContext": true - again got same exception.

Additional info:
```
.NET Command Line Tools (1.0.0-beta-002279)

Product Information:
 Version:     1.0.0-beta-002279
 Commit Sha:  76610c4cd4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
Microsoft.AspNetCore.SignalR.Server version 0.1.0-rc2-20466

**Comment by tbnguyen1407** [comment] 2016-04-19 09:06
Hi, any idea when this may be resolved?

I tried on version 0.1.0-rc3-20620 from aspnetcidev with the same error.

**Comment by nicolasr75** [comment] 2016-05-09 10:29
I would be very interested in that too. I had SignalR working with RC1 and now tried to switch to RC2. I don't need any new features in SignalR, just the simple hub that worked with RC1. But it doesn't work anymore since the hub type is not resolvable. This currently seems to be the only problem with it, at least for me.

Do I really have to wait until end of the year until SignalR gets included in ASP.NET Core?

**Comment by nicolasr75** [comment] 2016-05-09 22:48
I was able to make this work for me. Just in case anyone else is interested:

I switched my project to the dev feed, downloaded the SignalR source code and added it completely to my project to find out where the problem is. In my case all hubs are implemented in the main assembly.
The line
https://github.com/aspnet/SignalR-Server/blob/2781e94d6ad734a595564ed9c0de35a7b015e93f/src/Microsoft.AspNetCore.SignalR.Server/Hubs/DefaultAssemblyLocator.cs#L43
never returns true in my application! As far as I understand the intention of the code, it should find my main assembly but it does not. On the other hand, the class already loads the main assembly in the constructor which is all I need. I quick-fixed it by simply returning the main assembly from the GetAssemblies method. This way it at least works for me on Windows 10, I didn't test on other systems/platforms and would certainly ignore hubs in other assemblies.
The change suggested by pull request #165 did, by the way, not work for me.

Product Information:
 Version:     1.0.0-preview1-002699
 Commit Sha:  e53acd9bba

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

Microsoft.AspNetCore.SignalR.Server 0.1.0

**Comment by tbnguyen1407** [comment] 2016-05-10 03:55
Strange the change suggested in the PR worked for me. Still waiting for the official nuget for the fix so I don't have to rely on the source code ;S

**Comment by nicolasr75** [comment] 2016-05-10 07:37
I would love to try it but I am yet not very experienced with pull requests and building nuget packages. As it looks to me, the pull request was rejected and not merged because it failed one of the tests.  So would you share how you were able to use it so I can try it?
Making the source code ready for direct compiliation was indeed quite nasty :-(

**Comment by tbnguyen1407** [comment] 2016-05-10 07:51
For direct compilation, I pulled latest source code and made the some changes to the project files in addition to the suggested line (Dependency version change may not be necessary but it conflicts with my main assembly's version):

* Microsoft.AspNetCore.SignalR.Messaging
  * project.json

    ```
    Remove: "buildOptions::keyFile"
    Update: "System.Linq.Expressions" version from "4.0.11-*" to "4.1.0-*",
    ```
* Microsoft.AspNetCore.SignalR.Server
  * project.json
  
    ```
    Remove: "buildOptions::keyFile"
    Update: "Newtonsoft.Json" version from "8.0.2" to "8.0.3"
    ```
  * Hubs/DefaultAssemblyLocator.cs
  
    ```
    Remove: line 36 - "SelectMany(l => l.Assembly)"
    Update: line 37 - "Assembly.Load(assembly.Name)" to "Assembly.Load(new AssemblyName(assembly.Name))"
    ```

**Comment by nicolasr75** [comment] 2016-05-10 08:11
Ok, thanks very much for that. Sorry though I still don't get the _big picture_:
What did you then do with the modified code? _dotnet build_ and/or _dotnet publish_?
Did you build a nuget package and add it to a local package repository?

**Comment by tbnguyen1407** [comment] 2016-05-10 08:26
Sorry about the confusion. I just include and reference them as source projects along side with my app then build/publish them as a whole. I did not pack it into a separate nuget package.

That's why it's better if they merge the fix soon so we don't have to maintain our local hacked source.

**Comment by krontogiannis** [comment] 2016-05-10 08:27
I'm not sure if building from source signalr is needed. I was able to bypass the error by implementing a dummy [IAssemblyLocator](https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Hubs/IAssemblyLocator.cs) that returns the assembly containing my `Hub` and registering this locator in the `ConfigureServices` method.

**Comment by tbnguyen1407** [comment] 2016-05-10 08:31
That is also a good suggestion, if you don't want to mess with the code ;D

**Comment by nicolasr75** [comment] 2016-05-10 09:48
@krontogiannis Wow, that idea would have saved me about 4 hours yesterday! Unfortunately I wasn't aware of the possibility to replace the default assembly locator.
@tbnguyen1407 I gave replacing the default assembly locator a try and it works for me:
```
using System.Reflection;
using Microsoft.AspNetCore.SignalR.Hubs;
...

public class MyAssemblyLocator : IAssemblyLocator
{
	public IList<Assembly> GetAssemblies()
	{
		return new [] { Assembly.Load(new AssemblyName("MyMainAssembly")) };
	}
}
```
and in ConfigureServices after AddSignalR I have:

`services.AddSingleton<IAssemblyLocator, MyAssemblyLocator>();`

That seems to be all that is needed. Of course it would be nicer to dynamically determine the main assembly name. But then again, it's hopefully a temporary quick-fix anyway.

**Comment by Kagamine** [comment] 2016-05-15 16:48
Just do this will solve the problem:

Hubs/DefaultAssemblyLocator.cs

```
Remove: line 36 - "SelectMany(l => l.Assembly)"
Update: line 37 - "Assembly.Load(assembly.Name)" to "Assembly.Load(new AssemblyName(assembly.Name))"
```

it is no need to modify Microsoft.AspNetCore.SignalR.Messaging and project.json of Server.

**Comment by Kagamine** [comment] 2016-05-15 16:49
@tbnguyen1407  Can you open a PR to fix this issue?

**Comment by tbnguyen1407** [comment] 2016-05-15 16:52
Nah I'm not familiar with that stuff. Also @alfhenrik already did that; don't know why it was closed though.

**Comment by Kagamine** [comment] 2016-05-15 16:55
Because he modified the project.json files, it caused the source cannot pass the unit tests.

**Comment by tbnguyen1407** [comment] 2016-05-18 03:03
See how long it takes for them to merge. Don't think we will see rc2-final package on nuget so I still have to keep aspnetcirelease feed for now.

**Comment by Kagamine** [comment] 2016-05-18 03:10
@tbnguyen1407 I have created a feed which includes SignalR.Server rc2 & SignalR.Client. You can add this:

```
    <add key="Code Comb" value="https://www.myget.org/F/codecomb-rc2/api/v3/index.json" />
```

**Closed** 2016-05-18 17:06 UTC

**Comment by moozzyk** [comment] 2016-05-18 18:45
Note that SignalR-Server is not shipping on NuGet at the moment so you won't get SignalR-Server package from NuGet. The change was merged to the dev branch so the package with the fix won't show up on aspnetrelease/aspnetcirelase myget feeds. It will show up on in the aspnetvnext/aspntecidev myget feeds but the package will be rc3 and will have dependency on other rc3 packages. If you need this for your rc2 projects you may want to clone the repo and build locally or add it to your project and use a project to project reference.

**Comment by shutdown256** [comment] 2016-05-20 07:16
@Kagamine Awesome work. You saved me another sleepless night! Thank you.

**Comment by douglaswaights** [comment] 2016-06-03 07:42
@Kagamine Thankyou! The migration continues. Looks like a life saver! :-)

**Comment by Robynhu** [comment] 2016-06-05 01:07
Thank you!!!

**Comment by MarcinSzyszka** [comment] 2016-06-11 10:57
@moozzyk How I should do that? I cloned repo, builded and added to my solution. Then I added reference to project with SignalR in my web application. If I'm trying to start my application i'm getting error:
`Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.UseContentRoot(Microsoft.AspNetCore.Hosting.IWebHostBuilder, string)' and 'Microsoft.AspNetCore.Hosting.HostingAbstractionsWebHostBuilderExtensions.UseContentRoot(Microsoft.AspNetCore.Hosting.IWebHostBuilder, string)'`
Error is in Program.cs
![image](https://cloud.githubusercontent.com/assets/14890675/15984664/f6985364-2fd3-11e6-88d1-86265a288e3b.png)

**Comment by AndreiGorlov** [comment] 2016-06-11 15:25
@MarcinSzyszka
You can just copy'n'paste https://github.com/aspnet/SignalR-Server/blob/dev/src/Microsoft.AspNetCore.SignalR.Server/Hubs/DefaultAssemblyLocator.cs  into your project (rename class to something like HubCouldNotBeResolvedWorkaround), then in your ConfigureServices add 
```cs
services.AddSingleton<IAssemblyLocator, HubCouldNotBeResolvedWorkaround>();
```
just before services.AddSignalR();

**Comment by MarcinSzyszka** [comment] 2016-06-12 08:14
@AndreiGorlov Good idea. It works. Thanks

**Comment by Luigie** [comment] 2016-10-20 09:16
How can I use the connectionManager in the broadcastEngine class

 public class BroadcastEngine 
    {
        private readonly int pollingInterval;
        private readonly IHubContext _hub;

        public BroadcastEngine(IConnectionManager connectionManager)
        {
            _hub = connectionManager.GetHubContext<PerformanceHub>();
            this.pollingInterval = 1000;
        }

        public async Task OnMonitor()
        {
         
            //Monitor for infinity!
            while (true)
            {
                await Task.Delay(pollingInterval);

                IList<string> values = new List<string>();
                values.Add("Hopla1");
                values.Add("Hopla2");


                _hub.Clients.All.broadcastPerformance(values);
            }
        }

        public void Stop(bool immediate)
        {

            //HostingEnvironment.UnregisterObject(this);
        }
    }
}


---
this goes in Startup.cs 
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, IAssemblyLocator locator)
        {
... other stuff

   BroadcastEngine performanceEngine = new BroadcastEngine(**connectionManager**);
            Task.Factory.StartNew(async () => await performanceEngine.OnMonitor());

}
