### ISSUE TITLE
ServerSentEvent transport is broken

### ISSUE THREAD

**Issue by weinong** [aspnet/SignalR-Server#111] opened 2015-08-04 05:04 UTC
Hi,
Using the ASP.NET 5's SignalR package, I found the UWP app cannot call hub's method (return 500) whereas console app can. However, the server can call into UWP.
I also tried to run the SignalR server using ASP.NET 4, and the UWP app is able to call into server!
The repo is at https://github.com/weinong/SignalrTest

**Comment by weinong** [comment] 2015-08-07 17:44
The fact that UWP is unable to call hub's method is that its default transport is ServerSentEventsTransport because it uses portal library. When I change the console app to use SSE transport, it failed in the same way.
It appears ServerSentEvents transport is broken??

**Comment by weinong** [comment] 2015-08-07 19:23
Found the root cause. The exception thrown by SignalR server is incorrect content type `InvalidOperationException`. It's thrown in `ForeverTransport.ProcessSendRequest` when it's trying to read the form data and is expecting the request's content type to have either `application/x-www-form-urlencoded` or `multipart/form-data` which is actually null from the 2.2 SignalR client.

What is the right fix? The client should send the correct content type but that means the 3.0.0 SignalR-Server is broken against the existing 2.2 client with SSE transport which is the default in portable library. Or the server can fill in the content type if it's empty. Thoughts?

**Comment by weinong** [comment] 2015-08-11 04:10
@Eilon

**Comment by Eilon** [comment] 2015-08-11 04:42
@weinong the ASP.NET 5 SignalR packages are currently on hold. Can you email me to discuss your scenarios?

**Comment by moozzyk** [comment] 2016-08-24 22:46
Possibly related to https://github.com/aspnet/SignalR-Server/issues/91

**Comment by moozzyk** [comment] 2016-08-25 20:37
Dupe of #91

**Closed** 2016-08-25 21:29 UTC
Labels: duplicate
