### ISSUE TITLE
GetHubContext throws error RC2

### ISSUE THREAD

**Issue by wisien92** [aspnet/SignalR-Server#181] opened 2016-05-23 18:38 UTC
I get error thrown when calling GetHubContext 

>An exception of type 'System.InvalidOperationException' occurred in Microsoft.AspNetCore.SignalR.Server.dll but was not handled in user code

>Additional information: 'Loading' Hub could not be resolved.

below is constructor for my HomeController

```
private IHubContext loadingHub;
private IHubContext centralHub;

public HomeController(IConnectionManager connectionManager, IHostingEnvironment appEnvironment)
{
    loadingHub = connectionManager.GetHubContext<LoadingHub>();
    centralHub = connectionManager.GetHubContext<CentralViewHub>();
}
```

And here are parts of my Startup.cs

```
public void ConfigureServices(IServiceCollection services)
 {
    (....)
    services.AddMvc();
    services.AddSession();
    services.AddSignalR();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    (....)
     app.UseWebSockets();
     app.UseSignalR();
     app.UseStaticFiles();
     app.UseSession();
    (....)
 }
```

Am I missing some mapping or SignalR on RC2 works differently ?

EDIT:
I added  ` services.AddSingleton<ConnectionManager>();` in Startup.cs but nothing changed.

EDIT2:
And I have info  that I have specified 0.1.0-rc2-final but rc3 was used.

**Comment by moozzyk** [comment] 2016-05-23 20:42
This is probably a duplicate of https://github.com/aspnet/SignalR-Server/issues/164

**Closed by moozzyk** 2016-05-23 20:42 UTC

**Comment by wisien92** [comment] 2016-05-23 20:50
@moozzyk so I shoud try https://myget.org/gallery/aspnetrelease feed?

**Comment by moozzyk** [comment] 2016-05-23 21:12
@wisien92 - it's a bit more complicated than that at the moment. See: https://github.com/aspnet/SignalR-Server/issues/164#issuecomment-220121222
